apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mywordpress 
spec:
  maxReplicas: 6 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deployment 
  targetCPUUtilizationPercentage: 50 

