apiVersion: apps/v1 
kind: Deployment   
metadata: 
  name: wordpress-deployment 
  labels:   
    tier: frontend 
    app: mywordpress
spec: 
  selector:
    matchLabels:
       app: mywordpress 
  replicas: 2 
  template: 
    metadata:
       name: wordpress
       labels:
         app: mywordpress
    spec: 
       containers:
         - name: wordpress 
           image: wordpress 
           ports: 
           - containerPort: 80 
           resources: 
             requests: 
               cpu: 500m 
             limits:
               cpu: 1000m
