apiVersion: v1 
kind: Service 
metadata:
  name: wordpress-service 
  labels: 
    app: mywordpress
spec: 
  type: NodePort 
  ports: 
    - nodePort: 30008 
      port: 80 
      targetPort: 80 
  selector:
    app: mywordpress 

